#!/usr/bin/env node

// ============================================================================
// Follow DevOps — Prepare Digest
// ============================================================================
// Gathers everything the LLM needs to produce a DevOps digest:
// - Fetches X/Twitter feed, podcast feed, and blog feeds
// - Fetches the latest prompts (local only — no central server yet)
// - Reads the user's config (language, delivery method)
// - Outputs a single JSON blob to stdout
//
// Usage: node prepare-digest.js
// Output: JSON to stdout
// ============================================================================

import { readFile } from 'fs/promises';
import { existsSync } from 'fs';
import { join } from 'path';
import { homedir } from 'os';

// -- Constants ---------------------------------------------------------------

const USER_DIR = join(homedir(), '.follow-devops');
const CONFIG_PATH = join(USER_DIR, 'config.json');

const PROMPT_FILES = [
  'summarize-tweets.md',
  'summarize-podcast.md',
  'summarize-blogs.md',
  'digest-intro.md',
  'translate.md'
];

// Feed URLs — replace with a hosted server URL once available
// For now we fall back to local state files
const FEED_X_PATH = join(homedir(), '.follow-devops', 'feed-x.json');
const FEED_PODCASTS_PATH = join(homedir(), '.follow-devops', 'feed-podcasts.json');
const FEED_BLOGS_PATH = join(homedir(), '.follow-devops', 'feed-blogs.json');

// -- Helpers -----------------------------------------------------------------

async function fetchJSON(url) {
  try {
    const res = await fetch(url, { signal: AbortSignal.timeout(10000) });
    if (!res.ok) return null;
    return res.json();
  } catch {
    return null;
  }
}

async function readJSONFile(path) {
  try {
    const content = await readFile(path, 'utf-8');
    return JSON.parse(content);
  } catch {
    return null;
  }
}

// -- Main --------------------------------------------------------------------

async function main() {
  const errors = [];

  // 1. Read user config
  let config = {
    language: 'en',
    frequency: 'daily',
    delivery: { method: 'stdout' }
  };
  if (existsSync(CONFIG_PATH)) {
    try {
      config = JSON.parse(await readFile(CONFIG_PATH, 'utf-8'));
    } catch (err) {
      errors.push(`Could not read config: ${err.message}`);
    }
  }

  // 2. Load feeds — try local state files (generated by generate-feed.js if present)
  const feedX = await readJSONFile(FEED_X_PATH);
  const feedPodcasts = await readJSONFile(FEED_PODCASTS_PATH);
  const feedBlogs = await readJSONFile(FEED_BLOGS_PATH);

  if (!feedX) errors.push('No X feed found — run generate-feed.js or check ~/.follow-devops/feed-x.json');
  if (!feedPodcasts) errors.push('No podcast feed found');
  if (!feedBlogs) errors.push('No blog feed found');

  // 3. Load prompts — user custom > local skill copy
  const prompts = {};
  const scriptDir = decodeURIComponent(new URL('.', import.meta.url).pathname);
  const localPromptsDir = join(scriptDir, '..', 'prompts');
  const userPromptsDir = join(USER_DIR, 'prompts');

  for (const filename of PROMPT_FILES) {
    const key = filename.replace('.md', '').replace(/-/g, '_');
    const userPath = join(userPromptsDir, filename);
    const localPath = join(localPromptsDir, filename);

    if (existsSync(userPath)) {
      prompts[key] = await readFile(userPath, 'utf-8');
    } else if (existsSync(localPath)) {
      prompts[key] = await readFile(localPath, 'utf-8');
    } else {
      errors.push(`Could not load prompt: ${filename}`);
    }
  }

  // 4. Build output blob
  const output = {
    status: 'ok',
    generatedAt: new Date().toISOString(),
    config: {
      language: config.language || 'en',
      frequency: config.frequency || 'daily',
      delivery: config.delivery || { method: 'stdout' }
    },
    x: feedX?.x || [],
    podcasts: feedPodcasts?.podcasts || [],
    blogs: feedBlogs?.blogs || [],
    stats: {
      xBuilders: feedX?.x?.length || 0,
      totalTweets: (feedX?.x || []).reduce((sum, a) => sum + (a.tweets?.length || 0), 0),
      podcastEpisodes: feedPodcasts?.podcasts?.length || 0,
      blogPosts: feedBlogs?.blogs?.length || 0,
      feedGeneratedAt: feedX?.generatedAt || feedPodcasts?.generatedAt || feedBlogs?.generatedAt || null
    },
    prompts,
    errors: errors.length > 0 ? errors : undefined
  };

  console.log(JSON.stringify(output, null, 2));
}

main().catch(err => {
  console.error(JSON.stringify({ status: 'error', message: err.message }));
  process.exit(1);
});
